//
// RegistrationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class RegistrationAPI {
    /**
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiRegistrationPost(body: RegistrationRequest? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiRegistrationPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - POST /api/Registration
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiRegistrationPostWithRequestBuilder(body: RegistrationRequest? = nil) -> RequestBuilder<Void> {
        let path = "/api/Registration"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
