//
// AddNewsRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AddNewsRequest: Codable {


    public var title: String?

    public var body: String?

    public var sportTypeTag: String?

    public var goalTypeTag: String?

    public var difficultyLevelTag: String?
    public init(title: String? = nil, body: String? = nil, sportTypeTag: String? = nil, goalTypeTag: String? = nil, difficultyLevelTag: String? = nil) { 
        self.title = title
        self.body = body
        self.sportTypeTag = sportTypeTag
        self.goalTypeTag = goalTypeTag
        self.difficultyLevelTag = difficultyLevelTag
    }

}
