//
// AuthorizeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AuthorizeRequest: Codable {


    public var login: String?

    public var password: String?
    public init(login: String? = nil, password: String? = nil) { 
        self.login = login
        self.password = password
    }

}
