//
// TrainAddRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct TrainAddRequest: Codable {


    public var trainName: String?
    public init(trainName: String? = nil) { 
        self.trainName = trainName
    }

}
