//
// ActivityCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ActivityCreateRequest: Codable {


    public var activityName: String?

    public var startTime: String?

    public var endTime: String?

    public var location: String?
    public init(activityName: String? = nil, startTime: String? = nil, endTime: String? = nil, location: String? = nil) { 
        self.activityName = activityName
        self.startTime = startTime
        self.endTime = endTime
        self.location = location
    }

}
