//
// ApproachesAddRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ApproachesAddRequest: Codable {


    public var repeatCount: Int?

    public var workingWeight: Float?
    public init(repeatCount: Int? = nil, workingWeight: Float? = nil) { 
        self.repeatCount = repeatCount
        self.workingWeight = workingWeight
    }

}
