//
// ExerciseAddRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ExerciseAddRequest: Codable {


    public var exerciseName: String?
    public init(exerciseName: String? = nil) { 
        self.exerciseName = exerciseName
    }

}
