//
// RegistrationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct RegistrationRequest: Codable {


    public var email: String?

    public var password: String?
    public init(email: String? = nil, password: String? = nil) { 
        self.email = email
        self.password = password
    }

}
